name: Test and Train Model

on:
  push:
    branches: [ main, master ]

jobs:
  test-and-train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision
        pip install numpy pillow pytest

    - name: Run tests
      run: |
        python -m pytest tests/
        
    - name: Train model
      run: |
        python train.py

    - name: Upload model artifacts
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: best_model.pth
        retention-days: 5